steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/monkeydb:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'monkeydb:base',
    '-t', 'gcr.io/$PROJECT_ID/monkeydb:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/monkeydb:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/monkeydb:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/monkeydb:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/monkeydb:coverage',
    '.'
  ]
  
images: ['gcr.io/$PROJECT_ID/monkeydb:coverage', 'gcr.io/$PROJECT_ID/monkeydb:base', 'gcr.io/$PROJECT_ID/monkeydb:latest']


